package xmipp.jni;

public class XmippError {
   public static final int ERR_FIRST_LABEL = 0; /// 
   public static final int ERR_ARG_BADCMDLINE = 1;      /// < Errors on command line parameters.
   public static final int ERR_ARG_INCORRECT = 2;       /// < Incorrect argument received.
   public static final int ERR_ARG_MISSING = 3;         /// < Argument missing.
   public static final int ERR_ARG_DEPENDENCE = 4;      /// < Error with some arguments dependencies
   public static final int ERR_PROG_NOTDEF = 5;         /// < Required function not implemented
   public static final int ERR_DEBUG_TEST = 6;          /// < Just an error for debugging purpose.
   public static final int ERR_DEBUG_IMPOSIBLE = 7;     /// < Just for debugging, situation that can't happens
   public static final int ERR_DOCFILE = 8;             /// < Error in docfile format
   public static final int ERR_GRID = 9;                /// < Grid general error.
   public static final int ERR_GRID_SIZE = 10;           /// < Incorrect number of GRID volumes or shapes
   public static final int ERR_IMG_NOREAD = 11;          /// < Cannot read image from file.
   public static final int ERR_IMG_NOWRITE = 12;         /// < Cannot write image to file.
   public static final int ERR_IMG_UNKNOWN = 13;         /// < Unknown image type
   public static final int ERR_INDEX_OUTOFBOUNDS = 14;   /// < Index out of bounds.
   public static final int ERR_IO = 15;                  /// < Input/Output general error.
   public static final int ERR_IO_NOCLOSED = 16;         /// < File cannot be closed.
   public static final int ERR_IO_NOTEXIST = 17;         /// < File or directory does not exist.
   public static final int ERR_IO_NOTOPEN = 18;          /// < File cannot be open.
   public static final int ERR_IO_NOPERM = 19;           /// < Insufficient permissions to perform operation.
   public static final int ERR_IO_NOREAD = 20;           /// < Couldn't read from file.
   public static final int ERR_IO_NOWRITE = 21;          /// < Couldn't write to file.
   public static final int ERR_IO_NOTFILE = 22;          /// < It is not a file.
   public static final int ERR_IO_NOTDIR = 23;           /// < It is not a directory.
   public static final int ERR_IO_NOPATH = 24;           /// < Environment PATH cannot be read.
   public static final int ERR_IO_LOCKED = 25;	    	 /// < Error when locking/unloking a file.
   public static final int ERR_IO_SIZE = 26;             /// < Incorrect file size.
   public static final int ERR_MATRIX = 27;              /// < Matrix error.
   public static final int ERR_MATRIX_DIM = 28;          /// < Problem with matrix dimensions.
   public static final int ERR_MATRIX_EMPTY = 29;        /// < The matrix is empty.
   public static final int ERR_MATRIX_SIZE = 30;         /// < Problem with matrix size.
   public static final int ERR_MD = 31;                  /// < MetaData error.
   public static final int ERR_MD_NOACTIVE = 32;         /// < No active object in MetaData.
   public static final int ERR_MD_NOOBJ = 33;            /// < No exist requested object.
   public static final int ERR_MD_BADLABEL = 34;         /// < Unexpected label.
   public static final int ERR_MD_MISSINGLABEL = 35;     /// < Missing expected label
   public static final int ERR_MD_SQL = 36;              /// < Error in SQL of MetaData operations.
   public static final int ERR_MD_OBJECTNUMBER = 37;     /// < Incorrect number of objects in Metadata
   public static final int ERR_MD_BADTYPE = 38;          /// < Bad label type.
   public static final int ERR_MD_UNDEFINED = 39;        /// < Undefined label.
   public static final int ERR_MD_BADBLOCK  = 40;        /// < This block does not exist.
   public static final int ERR_MEM_BADREQUEST = 41;      /// < Bad amount of memory requested.
   public static final int ERR_MEM_NOTENOUGH = 42;       /// < There is not enough memory for allocation.
   public static final int ERR_MEM_NOTDEALLOC = 43;      /// < Memory has not been deallocated.
   public static final int ERR_MEM_NULLPOINTER = 44;     /// < Null pointer passed as parameter
   public static final int ERR_MMAP = 45;                /// < Global mmap error.
   public static final int ERR_MMAP_NOTADDR = 46;        /// < Map addressing of file has failed.
   public static final int ERR_MULTIDIM_DIM = 47;        /// < Incorrect MultidimArray dimensions
   public static final int ERR_MULTIDIM_SIZE = 48;       /// < Incorrect MultidimArray size
   public static final int ERR_MULTIDIM_EMPTY = 49;      /// < MultidimArray is empty.
   public static final int ERR_NOT_IMPLEMENTED = 50;     /// < Case or algorithm not implemented yet.
   public static final int ERR_NUMERICAL = 51;           /// < Error related to numerical calculation.
   public static final int ERR_PARAM_INCORRECT = 52;     /// < Parameter incorrect.
   public static final int ERR_PARAM_MISSING = 53;       /// < Parameter missing.
   public static final int ERR_PLANS_NOCREATE = 54;      /// < FFT Plan cannot be created.
   public static final int ERR_SELFILE = 55;             /// < Error in docfile format
   public static final int ERR_THREADS_NOTINIT = 56;     /// < Threads cannot be initiated.
   public static final int ERR_TYPE_INCORRECT = 57;      /// < Incorrect type received.
   public static final int ERR_UNCLASSIFIED = 58;        /// < Just to locate unclassified errors.
   public static final int ERR_VALUE_EMPTY = 59;         /// < Empty value.
   public static final int ERR_VALUE_INCORRECT = 60;     /// < Incorrect value received.
   public static final int ERR_VALUE_NOTSET = 61;         /// < Value has not been set.
   public static final int ERR_LAST_LABEL = 62; /// 
}
